### ISSUE TITLE
block_until_ready doesn't timeout if the api key is invalid

### ISSUE THREAD

**Issue by psilospore** [splitio/ruby-client#343]
Hi,

I would like to handle the case where the api key for split is invalid and we recover by assuming any feature's using split are disabled by default.

I was expecting to just rescue after creating the split factory, client, or calling `block_until_ready`.
However, it seems the `block_until_ready` method doesn't timeout when the api key is invalid.

Would you have an alternative suggestion such as a way to validate the API key first or should `block_until_ready` timeout eventually?

Current behavior:

```
00:28:00 web.1       | Unexpected status code while fetching splits: 404. Check your API key and base URI
00:28:00 web.1       | [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
00:28:02 worker.1    | Unexpected status code while fetching splits: 404. Check your API key and base URI
00:28:02 worker.1    | [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
```

That repeats indefinitely.

Thanks!

**Comment by chillaq** [comment]
Hi Syed, thanks for the info, will repro and get back to you.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Syed, I can repro, I actually see several exceptions in the log, but the rescue block never called. I submitted a bug.

require 'splitclient-rb'
options = {block_until_ready: 5,
debug_enabled: true,
transport_debug_enabled: true}  
begin  
split_factory = SplitIoClient::SplitFactoryBuilder.build("sdk", options)
split_client = split_factory.client
split_client.block_until_ready 
rescue SplitIoClient::SDKBlockerTimeoutExpiredException 
puts 'SDK is not ready. Decide whether to continue or abort execution'  
end

**Comment by psilospore** [comment]
Thanks! @chillaq

**Comment by chillaq** [comment]
Hi Syed, actually I cannot repro with Ruby SDK 7.2.0, here is the output log

, [2020-10-21T11:23:45.331813 #3283]  INFO – : Loaded Ruby SDK v7.2.0 in the standalone mode
I, [2020-10-21T11:23:45.331894 #3283]  INFO – : Loaded cache class: SplitIoClient::Cache::Adapters::MemoryAdapter
D, [2020-10-21T11:23:45.332140 #3283] DEBUG – : Starting push mode ...
D, [2020-10-21T11:23:45.332281 #3283] DEBUG – : Synchronizing Splits and Segments ...
D, [2020-10-21T11:23:45.333590 #3283] DEBUG – : GET https://sdk.split.io/api/splitChanges proxy: 
I, [2020-10-21T11:23:45.333822 #3283]  INFO – : Starting metrics service
I, [2020-10-21T11:23:45.333852 #3283]  INFO – : Starting impressions service
I, [2020-10-21T11:23:45.338053 #3283]  INFO – : Starting impressions count service
D, [2020-10-21T11:23:45.338343 #3283] DEBUG – : GET https://auth.split.io/api/auth proxy: 
I, [2020-10-21T11:23:45.338401 #3283]  INFO – : Starting events service
D, [2020-10-21T11:23:45.343671 #3283] DEBUG – : No events to report
D, [2020-10-21T11:23:45.338452 #3283] DEBUG – : No latencies to report.
D, [2020-10-21T11:23:45.343867 #3283] DEBUG – : No counts to report.
D, [2020-10-21T11:23:45.338609 #3283] DEBUG – : No impressions count to send
D, [2020-10-21T11:23:45.338547 #3283] DEBUG – : No impressions to report
E, [2020-10-21T11:23:45.416795 #3283] ERROR – : Unexpected status code while fetching splits: 404. Check your API key and base URI
W, [2020-10-21T11:23:45.416983 #3283]  WARN – : [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/splits.rb:36:in `since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:71:in `splits_since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:32:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `synchronize'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:56:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:55:in `loop'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:55:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:32:in `sync_all'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/sync_manager.rb:70:in `block in stream_start_thread'
D, [2020-10-21T11:23:45.654549 #3283] DEBUG – : Error connecting to: https://auth.split.io/api/auth. Response status: 401
D, [2020-10-21T11:23:45.654614 #3283] DEBUG – : Auth service response push_enabled: false
D, [2020-10-21T11:23:45.654642 #3283] DEBUG – : Dispatching disconnect
I, [2020-10-21T11:23:45.654923 #3283]  INFO – : Starting splits fetcher service
D, [2020-10-21T11:23:45.655825 #3283] DEBUG – : GET https://sdk.split.io/api/splitChanges proxy: 
I, [2020-10-21T11:23:45.662850 #3283]  INFO – : Starting segments fetcher service
E, [2020-10-21T11:23:46.274221 #3283] ERROR – : Unexpected status code while fetching splits: 404. Check your API key and base URI
W, [2020-10-21T11:23:46.274303 #3283]  WARN – : [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/splits.rb:36:in `since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:71:in `splits_since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:32:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `synchronize'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:61:in `block (2 levels) in splits_thread'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:60:in `loop'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:60:in `block in splits_thread'
D, [2020-10-21T11:23:46.274515 #3283] DEBUG – : Splits fetcher is sleeping for: 3.4499999999999997 seconds
D, [2020-10-21T11:23:47.509559 #3283] DEBUG – : GET https://sdk.split.io/api/splitChanges proxy: 
E, [2020-10-21T11:23:47.612438 #3283] ERROR – : Unexpected status code while fetching splits: 404. Check your API key and base URI
W, [2020-10-21T11:23:47.713477 #3283]  WARN – : [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/splits.rb:36:in `since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:71:in `splits_since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:32:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `synchronize'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:56:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:55:in `loop'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:55:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:32:in `sync_all'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/sync_manager.rb:70:in `block in stream_start_thread'
D, [2020-10-21T11:23:49.757252 #3283] DEBUG – : GET https://sdk.split.io/api/splitChanges proxy: 
E, [2020-10-21T11:23:50.062392 #3283] ERROR – : Unexpected status code while fetching splits: 404. Check your API key and base URI
W, [2020-10-21T11:23:50.062454 #3283]  WARN – : [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/splits.rb:36:in `since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:71:in `splits_since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:32:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `synchronize'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:61:in `block (2 levels) in splits_thread'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:60:in `loop'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:60:in `block in splits_thread'
D, [2020-10-21T11:23:50.062565 #3283] DEBUG – : Splits fetcher is sleeping for: 3.7 seconds
D, [2020-10-21T11:23:51.838315 #3283] DEBUG – : GET https://sdk.split.io/api/splitChanges proxy: 
E, [2020-10-21T11:23:52.044139 #3283] ERROR – : Unexpected status code while fetching splits: 404. Check your API key and base URI
W, [2020-10-21T11:23:52.044228 #3283]  WARN – : [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/splits.rb:36:in `since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:71:in `splits_since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:32:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `synchronize'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:56:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:55:in `loop'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:55:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:32:in `sync_all'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/sync_manager.rb:70:in `block in stream_start_thread'
D, [2020-10-21T11:23:53.788277 #3283] DEBUG – : GET https://sdk.split.io/api/splitChanges proxy: 
E, [2020-10-21T11:23:53.994739 #3283] ERROR – : Unexpected status code while fetching splits: 404. Check your API key and base URI
W, [2020-10-21T11:23:54.095131 #3283]  WARN – : [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/splits.rb:36:in `since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:71:in `splits_since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:32:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `synchronize'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:61:in `block (2 levels) in splits_thread'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:60:in `loop'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:60:in `block in splits_thread'
D, [2020-10-21T11:23:54.195853 #3283] DEBUG – : Splits fetcher is sleeping for: 4.95 seconds
D, [2020-10-21T11:23:59.338647 #3283] DEBUG – : GET https://sdk.split.io/api/splitChanges proxy: 
E, [2020-10-21T11:24:00.364280 #3283] ERROR – : Unexpected status code while fetching splits: 404. Check your API key and base URI
W, [2020-10-21T11:24:00.364350 #3283]  WARN – : [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/splits.rb:36:in `since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:71:in `splits_since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:32:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `synchronize'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:61:in `block (2 levels) in splits_thread'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:60:in `loop'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:60:in `block in splits_thread'
D, [2020-10-21T11:24:00.364473 #3283] DEBUG – : Splits fetcher is sleeping for: 3.5 seconds
D, [2020-10-21T11:24:00.464661 #3283] DEBUG – : GET https://sdk.split.io/api/splitChanges proxy: 
**SDK is not ready. Decide whether to continue or abort execution**
E, [2020-10-21T11:24:00.469736 #3283] ERROR – : get_treatment: the SDK is not ready, the operation cannot be executed
treatment control
I, [2020-10-21T11:24:00.469968 #3283]  INFO – : Split SDK shutdown started...
I, [2020-10-21T11:24:00.469995 #3283]  INFO – : Split client shutdown started...
D, [2020-10-21T11:24:00.470552 #3283] DEBUG – : POST https://events.split.io/api/testImpressions/bulk [{"f":"sample_feature","i":[{"k":"bob","t":"control","m":1603304640469,"b":null,"r":"not ready","c":null,"pt":null}]}]
D, [2020-10-21T11:24:00.470585 #3283] DEBUG – : POST https://events.split.io/api/testImpressions/bulk
E, [2020-10-21T11:24:00.978057 #3283] ERROR – : Unexpected status code while posting impressions: 400. - Check your API key and base URI
W, [2020-10-21T11:24:00.978118 #3283]  WARN – : [splitclient-rb] Unexpected exception in post_impressions: #<RuntimeError: Split SDK failed to connect to backend to post impressions> Split SDK failed to connect to backend to post impressions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/impressions.rb:24:in `post'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/senders/impressions_sender.rb:47:in `post_impressions'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/senders/impressions_sender.rb:36:in `rescue in block in impressions_thread'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/senders/impressions_sender.rb:27:in `block in impressions_thread'
I, [2020-10-21T11:24:00.978135 #3283]  INFO – : Posting impressions due to shutdown
D, [2020-10-21T11:24:00.978604 #3283] DEBUG – : POST https://events.split.io/api/metrics/time {"name":"sdk.get_treatment","latencies":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}
D, [2020-10-21T11:24:00.978633 #3283] DEBUG – : POST https://events.split.io/api/metrics/time
E, [2020-10-21T11:24:01.191034 #3283] ERROR – : Unexpected status code while fetching splits: 404. Check your API key and base URI
W, [2020-10-21T11:24:01.191118 #3283]  WARN – : [splitclient-rb] Unexpected exception in fetch_splits: #<RuntimeError: Split SDK failed to connect to backend to fetch split definitions> Split SDK failed to connect to backend to fetch split definitions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/splits.rb:36:in `since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:71:in `splits_since'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:32:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `synchronize'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/fetchers/split_fetcher.rb:31:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:56:in `block in fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:55:in `loop'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:55:in `fetch_splits'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/synchronizer.rb:32:in `sync_all'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/sync_manager.rb:70:in `block in stream_start_thread'
E, [2020-10-21T11:24:01.494817 #3283] ERROR – : Unexpected status code while posting time metrics: 400 - Check your API key and base URI
W, [2020-10-21T11:24:01.495002 #3283]  WARN – : [splitclient-rb] Unexpected exception in post_metrics: #<RuntimeError: Split SDK failed to connect to backend to post metrics> Split SDK failed to connect to backend to post metrics
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/metrics.rb:56:in `log_status'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/metrics.rb:28:in `block in post_latencies'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/metrics.rb:23:in `each'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/metrics.rb:23:in `post_latencies'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/metrics.rb:13:in `post'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/senders/metrics_sender.rb:44:in `post_metrics'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/senders/metrics_sender.rb:36:in `rescue in block in metrics_thread'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/senders/metrics_sender.rb:27:in `block in metrics_thread'
I, [2020-10-21T11:24:01.495044 #3283]  INFO – : Posting metrics due to shutdown
D, [2020-10-21T11:24:01.495119 #3283] DEBUG – : No events to report
I, [2020-10-21T11:24:01.495135 #3283]  INFO – : Posting events due to shutdown
D, [2020-10-21T11:24:01.495544 #3283] DEBUG – : POST https://events.split.io/api/testImpressions/count {"pf":[{"f":"sample_feature","m":1603303200000,"rc":1}]}
D, [2020-10-21T11:24:01.495651 #3283] DEBUG – : POST https://events.split.io/api/testImpressions/count
E, [2020-10-21T11:24:02.010419 #3283] ERROR – : Unexpected status code while posting impressions count: 400. - Check your API key and base URI
W, [2020-10-21T11:24:02.113575 #3283]  WARN – : [splitclient-rb] Unexpected exception in post_impressions_count: #<RuntimeError: Split SDK failed to connect to backend to post impressions> Split SDK failed to connect to backend to post impressions
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/engine/api/impressions.rb:41:in `post_count'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/senders/impressions_count_sender.rb:45:in `post_impressions_count'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/senders/impressions_count_sender.rb:38:in `rescue in block in impressions_count_thread'
/Library/Ruby/Gems/2.3.0/gems/splitclient-rb-7.2.0/lib/splitclient-rb/cache/senders/impressions_count_sender.rb:29:in `block in impressions_count_thread'
I, [2020-10-21T11:24:02.113612 #3283]  INFO – : Posting impressions count due to shutdown
I, [2020-10-21T11:24:02.113681 #3283]  INFO – : Split client shutdown complete
I, [2020-10-21T11:24:02.113715 #3283]  INFO – : Split SDK shutdown complete

**Comment by sanzmauro** [comment]
Hi @psilospore !

The `block_until_ready` will throw a `SplitIoClient::SDKBlockerTimeoutExpiredException` after the configured time expires, which is 15 seconds by default.
You could configure it to a shorter time, like 5 seconds which should be plenty of time in most cases:
```ruby
options = {block_until_ready: 5}
split_factory = SplitIoClient::SplitFactoryBuilder.build(your-api-key, options)
```
If your goal was to have it fail instantly, I can track an enhancement request so that `block_until_ready` expires earlier if the api key is incorrect so the product team can properly prioritize.

And in regards with the behavior of the logs, it seems to be working as expected.

Mauro

**Comment by NicoZelaya** [comment]
@psilospore do you require further assistance here? Were you able to achieve what you need?

**Comment by psilospore** [comment]
Sorry for the late response.

@sanzmauro I do see that it throws and I'm able to rescue for a timeout exception, but if I have an invalid API key there's no exception thrown although I can see there's an auth error in the log.

I think I said it should timeout and implying that a timeout exception should be thrown. But that might have been a bad way to describe the expected behavior. Sorry about that.

I suppose in this case I would expect it to throw some kind of exception related to an invalid API key and I would be able to rescue from that.

Currently, it does not throw anything when there's an invalid API key.

@chillaq did you test it out with an invalid API key? I am using ruby 2.6.6.

**Comment by chillaq** [comment]
Hi @psilospore , yes, I tried invalid API Key and the rescue code block was executed, as shown in the log file. Could you try SDK version 2.7.0?

Thanks

**Comment by psilospore** [comment]
Hmm I was using splitclient-rb 7.2. I might close this for now though as this case probably won't happen for us. Thanks!
